### ISSUE TITLE
Unable to pull saved creds from pwd file

### ISSUE THREAD

**Issue by digitalexpl0it** [tfarray/SmartSheet_Powershell_Module#4] opened 2017-06-29 21:51 UTC
After running 
`Set-SmartSheetAPIToken  "MYTOKEN" -pwdfile "C:\Users\USER\AppData\Roaming\SS_PS.pwd" -user "USER"`

The pwd file is created but when I try to pull from the pwd get-smartsheet asks for my users password and token each time. 
`$SSToken = get-SmartSheetAPIToken -pwdfile "C:\Users\USER\AppData\Roaming\SS_PS.pwd" -user "USER"
get-smartsheet`

how can I run the script without asking for a token and a password?

**Comment by tfarray** [comment] 2017-06-30 08:06
When I wrote this, I had the intent to be able to use different accounts. but you don't need it.

Forget about those difficult switches, you don’t need them.

Just run :
Set-SmartSheetAPIToken "MYTOKEN"
get-smartsheet SheetName

**Comment by digitalexpl0it** [comment] 2017-06-30 14:30
I tried that, it does work, but it asks be for a password and token each time the script is ran. I am trying to create a tool to sync with smartsheet and will run automatically so having to enter the password and token each time would work for me.

**Comment by tfarray** [comment] 2017-07-03 08:10
This is an unexpected behavior.

For a Single user, on a single computer, the goal of this module was to get rid of this password.
This will not work if you use another account or if you move computer, but I don’t think this is the case.

Let me review my code and I’ll try to come back. If you find anything please let me know

Thomas

**Comment by tfarray** [comment] 2017-07-03 08:25
I tried on a new host,

I set credentials, closed the powershell command line, reloaded it. And it still worked.

Can you please run those commands:

·        Set-SmartSheetAPIToken –Verbose

·        Get-SmartSheetAPIToken –Verbose

Close the powershell session, open a new one and do

·        Get-SmartSheetAPIToken –Verbose

I need all the dialogs in yellow. Paste all of that here, it will help me understand what happens.

Thomas

**Comment by digitalexpl0it** [comment] 2017-07-03 14:51
When i am running the following:

·        Set-SmartSheetAPIToken –Verbose
·        Get-SmartSheetAPIToken –Verbose

The following error appears



> Please enter your password for the account user1: ************
> out-file : Illegal characters in path.
> At C:\Program Files (x86)\WindowsPowerShell\Modules\SmartSheet\SmartSheet.psm1:83 char:46
> +         $SecureString | ConvertFrom-SecureString | out-file $pwdfile
> +                                                    ~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OpenError: (:) [Out-File], ArgumentException
>     + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
> 
> Crendentials stored to â€Verbose
> Get-SmartSheetAPIToken â€Verbose
> 
> When I closed powershell then ran 
> 
> Get-SmartSheetAPIToken –Verbose
> 
> I get the following
> 
> PS U:\Powershell\Smartsheet> Get-SmartSheetAPIToken –Verbose
> Please enter your SmartSheet API Token for the account user1: ************
> VERBOSE: SmartSheet token read for derrick-rose
> 
> UserName                         Password
> --------                         --------
> user1 System.Security.SecureString


Environment:
Windows Server 2016
PSVersion: 5.1.14393.1358
.NET 4.7

**Comment by digitalexpl0it** [comment] 2017-07-03 14:55
Just realized, I am running 64 bit powershell, I moved the smartsheet cmdlets to the 64 bit powershell folder and get the following 

Set-SmartSheetAPIToken –Verbose
Please enter your password for the account user1: ************
Crendentials stored to C:\Users\user1\AppData\Roaming\user1_SSToken.pwd

Get-SmartSheetAPIToken –Verbose
VERBOSE: SmartSheet token read for user1

UserName                         Password
>--------                         --------
user1 System.Security.SecureString

**Comment by digitalexpl0it** [comment] 2017-07-03 14:58
I closed powershell and re-opened it. Now running Get-SmartSheetAPIToken –Verbose is pulling the username/password

**Comment by digitalexpl0it** [comment] 2017-07-03 15:06
Looks like that was the main issue, though now if I execute Get-SmartSheetAPIToken, it is asking for my API token each time. The username/password isnt asked anymore which is good

**Comment by tfarray** [comment] 2017-07-03 15:12
What is strange there, is that there should not be any issue with 64 bit version of powershell.

As said in the error, the issue comes from the “out-file” command, which has nothing to do with 64 bit IMO.

I have no clue about the reasons of that error, it seems the path of the file is not willing to get opened.

Thomas

**Comment by digitalexpl0it** [comment] 2017-07-03 15:15
Does the API token get stored int he pwd file?

**Comment by digitalexpl0it** [comment] 2017-07-03 15:17
I removed all the pwd files, and specified a folder on my C: drive (C:\test) with full permissions. Created the pwd file there, then when I close out powershell and run Get-SmartSheetAPIToken  -pwdfile "C:\test\SS_PS.pwd" I am prompted for the API token, but not the username/password

**Comment by tfarray** [comment] 2017-07-03 15:22
When no switch is stipulated, the data is stored in this file :

C:\users\[username]\AppData\Roaming\[username]_SSToken.pwd

It is using Windows Data Protection API, and you the account of the creator may decrypt the file.

Thomas

**Comment by tfarray** [comment] 2017-07-03 20:27
closing this issue. re open if you think it is not
I am new to Github, not sure how this works, but re open if needed.

**Closed as completed** 2017-07-03 20:26 UTC
